### ISSUE TITLE
Use printImage , but not clear.

### ISSUE THREAD

**Issue by ianhwu** [envoy/BRPtouchPrinterKit#2]
I used this:
-(int) printImage: (CGImageRef) imageRef copy: (int) nCopy

It printed label, but the label all white and black.

**Comment by ropiku** [comment]
This is just wrapping the Brother SDK nicely for Cocoapods but we cannot help with SDK issues. Please contact [Brother](http://www.brother.com/product/dev/mobile/ios/download/index.htm).
