### ISSUE TITLE
Detect Printer Disconnecting

### ISSUE THREAD

**Issue by maulikpat** [envoy/BRPtouchPrinterKit#3]
Hello,

I am using BRPtouchPrinterKit 1.2.8 

Currently I am checking Printer connection/availability by  `isPrinterReady`  method. This is fine to check before printing.

But, Is it possible to detect printer disconnections by any event or delegate ? I want to show an alter if printer got switch off and network issue with connection.

Thanks

**Comment by ropiku** [comment]
@maulikpat This is just a cocoapods wrapper for [Brother Print SDK](http://www.brother.com/product/dev/mobile/ios/). We are not affiliated with Brother nor can we provide support.

Personally I am not aware of such a method, you could have a timer that regularly checks `isPrinterReady`.

**Comment by maulikpat** [comment]
ok thanks for the reply and info.
